/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:dcef578a-f0a8-4319-95ae-0a57ee34026d",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_SFgxOkFUW",
    "aws_user_pools_web_client_id": "2r636u9u5vl45va3tgcjci6b0a",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://wvknyu6bwzcuzpyv3kyerfxn6u.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
